### ISSUE TITLE
NeuralSORT可以在线推理吗？

### ISSUE THREAD

**Issue by Project627** [dyhBUPT/iKUN#11]
大佬您好，我正在学习您的论文，想请教下NeuralSORT属于在线推理的算法吗？如果不属于，可以改进成在线推理的嘛？谢谢大佬

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.
The NeuralSORT is developed based on DeepSORT, but we use the offline linear interpolation. If we abondan interpolation, NeuralSORT is online.

**Comment by Project627** [comment]
Thank you for your kindly reply, I still have a question I'd like to ask: After adding ikun to NeuralSORT, is it still capable of online inference? Or is ikun a post-processing module that can incorporate text, and the model cannot perform online inference after adding ikun?

**Comment by dyhBUPT** [comment]
That's a good question.

Indeed, iKUN itself can work in an online manner, therefore "online tracker + iKUN" is still online.

However, for simplicity, this code base is written in an offline manner. If you need work on online scenes, you need to re-design the inference pipeline.

**Comment by Project627** [comment]
Understood, thank you for your explanation.
