### ISSUE TITLE
有demo.py样例吗

### ISSUE THREAD

**Issue by dengxiongshi** [dyhBUPT/iKUN#14]
@dyhBUPT 你好，运行样例有吗

**Comment by dyhBUPT** [comment]
Hi, sorry and I don't prepare demos. There are some visualization results in our paper.

**Comment by dengxiongshi** [comment]
> Hi, sorry and I don't prepare demos. There are some visualization results in our paper.

@dyhBUPT 你好，请问下论文中使用的NKF是在代码中的什么地方

**Comment by dyhBUPT** [comment]
I'm sorry but the codes for MOT (including NKF / NeuralSORT) are not released for now. This repo focuses on the iKUN model.

**Comment by zt20001126** [comment]
你好，只有小黑子，没有demo.py样例。

**Comment by TernencezzZ** [comment]
You better be

**Comment by xyl-507** [comment]
> I'm sorry but the codes for MOT (including NKF / NeuralSORT) are not released for now. This repo focuses on the iKUN model.

Thanks for your contribution. Is there a plan to release it?

**Comment by dyhBUPT** [comment]
> > I'm sorry but the codes for MOT (including NKF / NeuralSORT) are not released for now. This repo focuses on the iKUN model.
> 
> @dyhBUPT Thanks for your contribution. Is there a plan to release it?

Sorry, I don't have time to do this for now. You can try to reproduce the results based on DeepSORT.
