### ISSUE TITLE
Inquiry Regarding the Location of NeuralSORT Code

### ISSUE THREAD

**Issue by Liamzh0331** [dyhBUPT/iKUN#25]
I am currently exploring your repository and was particularly interested in the NeuralSORT project.  However, I am having some difficulty locating the relevant code for NeuralSORT within the repository.
Could you please guide me on where I can find the code or provide any additional instructions if it is located in a different branch or repository?
Thank you very much for your time and assistance.

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.
Unfortunately, this repo only includes codes of the `iKUN` model, not NeuralSORT. I don't have time to prepare it for now.
It may not be hard for you to reproduce our reported results based on DeepSORT or StrongSORT.
