### ISSUE TITLE
Discrepancies in Test Results and Performance with 'Cascade Attention' Mode

### ISSUE THREAD

**Issue by Liamzh0331** [dyhBUPT/iKUN#27]
Hi,

I encountered a couple of issues while running the tests and training. First, when I run python test.py --test_ckpt iKUN.pth, the results match those reported in the paper. However, when I use python test.py --kum_mode 'cascade attention' --test_ckpt iKUN_cascade_attention.pth, the results are significantly different and much worse than what's reported in the paper. Could you please help me understand why this might be happening?

Additionally, I trained a model using python train.py --exp_name my_exp --kum_mode 'cascade attention', and the resulting weights (epoch99.pth) also perform poorly during testing. Is it possible that there’s an issue with how I set some of the hyperparameters? I would greatly appreciate your guidance on this.

Thanks in advance for your help!

**Comment by goldentimecoolk** [comment]
Hi, @Liamzh0331 how do you address the discrepancies? I observe the same issue. My HOTA is about 10 points lower than reported.
