### ISSUE TITLE
oracle experiments

### ISSUE THREAD

**Issue by ZHuangyeei** [dyhBUPT/iKUN#30]
Could you tell me how to conduct oracle experiments on TransRMOT, please?

**Comment by dyhBUPT** [comment]
Hi, our oracle exps are conducted by "correcting the predicted locations based on GTs", and "no bboxes are removed or added".
![image](https://github.com/user-attachments/assets/2eaa0814-77ab-4460-905d-737f48ee97e8)

**Comment by ZHuangyeei** [comment]
Is this step performed during inference phrase? It disregards the errors associated with the bounding boxes, while the referring score still corresponds to the predicted bounding boxes, correct?

**Comment by ZHuangyeei** [comment]
Is this step performed during inference phrase? It disregards the errors associated with the bounding boxes, while the referring score still corresponds to the predicted bounding boxes, right?

**Comment by dyhBUPT** [comment]
1. The step worked after inference and before evaluating. That is, we modify the prediction results with gts.
2. It only disregards the "localization errors", that is [x,y,w,h].
