### ISSUE TITLE
how fast is iKUN？

### ISSUE THREAD

**Issue by zhongqiu1245** [dyhBUPT/iKUN#31]
你好，非常感谢你的工作！
请问iKUN网络有测过速度嘛？比如在xx显卡上能否达到xxfps？
以及支持tensorrt加速吗？
谢谢！

**Comment by dyhBUPT** [comment]
hi, thanks for your interest.
Please refer to Table.7 in our [latest paper](https://arxiv.org/pdf/2312.16245) for training and inferring speed.
But it only provides time cost, not FPS.

**Comment by dyhBUPT** [comment]
TensorRT is not considered in our work, you can try it~

**Comment by zhongqiu1245** [comment]
thx!
