### ISSUE TITLE
Suggestions for supplementing experimental data / 补充实验的建议

### ISSUE THREAD

**Issue by tylzh97** [dyhBUPT/iKUN#4]
The method of using  insertable  Knowledge Unification Network for RMOT tasks is novel. The KUM module can extract visual features well, thereby improving the recognition accuracy of the target. The experimental part provides a new Refer-Dance dataset based on the DanceTrack dataset, which proves that ikun indeed has a good effect on the RMOT task. However, according to my observation, the target size in the dataset is relatively balanced. The article does not prove the tracking ability of ikun on different scales and different targets. 
Can some experiments be added, such as **tracking a picture of a person dancing and playing basketball at the same time**, and tracking the positions of the basketball and the ~~chicken~~ person at the same time? 
For example: 
![fbe1f235e16f9781e93f3ef8bd4dd88d](https://github.com/dyhBUPT/iKUN/assets/24435007/490d3952-4813-4560-b0ec-493736f745d6)
---

使用ikun进行RMOT任务的方法令人眼前一亮, KUM模块能够很好的提取视觉特征, 从而提高目标的识别精度. 实验部分在DanceTrack数据集的基础上, 提供了新的Refer-Dance数据集, 证明了在RMOT任务上ikun确实有很好的效果. 然而据我的观察, 数据集中的目标大小较为均衡, 文章并没有证明ikun在不同尺度上不同目标的追踪能力. 
能否补充一些实验, 例如**追踪一个人一边跳舞一边打篮球的**动作, 同时追踪篮球与~~鸡~~人的位置呢?

**Comment by dyhBUPT** [comment]
a good idea

**Comment by wsw321** [comment]
hahaha

**Comment by xyl-507** [comment]
+1

**Comment by KainingYing** [comment]
附议~

我还是被骗了
