### ISSUE TITLE
Refer-Dance  dataset

### ISSUE THREAD

**Issue by Kid-Young** [dyhBUPT/iKUN#5]
请问作者可以公开Refer-Dance数据集吗？ 
顺便问一下 Figure 7   Row 3 的练习室是JYP的练习室吗？ 人物是Twice吗？还是NiziU？

**Comment by dyhBUPT** [comment]
Hi, the link for downloading Refer-Dance has been provided in README.
For your second question, I have no idea. It's from the DanceTrack dataset.

**Comment by Kid-Young** [comment]
> Hi, the link for downloading Refer-Dance has been provided in README. For your second question, I have no idea. It's from the DanceTrack dataset.

Yes, it's twice, I saw BTS, EXO, BP, Itzy in this dataset.
