### ISSUE TITLE
amagi

### ISSUE THREAD

**Issue by dblCh** [dyhBUPT/iKUN#6]
Dear dyh,

I am writing to address the serious infringement of the rights of our principal on your github.    The content in question has garnered significant views and has a wide-reaching impact, causing severe harm.    This material not only involves intentional defamation and misuse of the individual's likeness but also incorporates numerous derogatory terms.    Additionally, there is malicious editing of the principal's performance videos.

The creation, uploading, dissemination, and re-sharing of this content have infringed upon our principal's rights, including but not limited to the right to reputation, image, and performer's rights.    Some individuals and self-media entities involved may even be liable for criminal offenses, contributing to a substantial negative societal impact.

We urgently request the removal of the aforementioned content from your platform and any associated networks.    Furthermore, we demand that you take immediate action to investigate and rectify the situation.    Failure to comply may result in legal proceedings to protect our principal's rights.

Bring your paper with you to court！！！

Sincerely,

real ikun

**Comment by OvOzzzzzzz** [comment]
哦呀哈哈amagi
